### Registrar cliente
POST http://localhost:9091/v1/api/customer/save
Content-Type: application/json 

{
    "name": "Juan",
    "lastName": "Illanes",
    "email": "Juan@ucb.edu.bo"
}

#### Obtener todos los cliente
GET http://localhost:9091/v1/api/customer/all
Accept: application/json

#### Obtener todos los cliente
GET http://localhost:9091/v1/api/customer?customerId=1
Accept: application/json





