#### 
GET http://localhost:9091/v1/api/customer/test
Accept: application/json

### Registrar cliente por MS-COSTUMER
POST http://localhost:9091/v1/api/customer/save
Content-Type: application/json 

{
    "name": "Juan",
    "lastName": "Illanes",
    "email": "Juan@ucb.edu.bo"
}

### Registrar cliente pasando por GATEWAY
POST http://localhost:8282/ms-custumer/v1/api/customer/save
Content-Type: application/json 

{
    "name": "Juan",
    "lastName": "Illanes",
    "email": "Juan@ucb.edu.bo"
}

### refrescar actuator
POST http://localhost:9091/actuator/refresh



#### Obtener todos los cliente
GET http://localhost:9091/v1/api/customer/all
Accept: application/json

#### Obtener todos los cliente
GET http://localhost:9091/v1/api/customer?customerId=1
Accept: application/json





